feat(QA): add new question to the list
gazprom-neft/consta-landing pull request #14
Opened 2021-09-13 10:52 UTC by N1MBER

* Add new question to the FAQ list

issue -  [#1415](https://github.com/gazprom-neft/consta-uikit/issues/1415)

2021-09-14 11:06 UTC, gizeasy requested changes

2021-09-14 11:06 UTC, gizeasy commented on src/modules/api/links/index.tsx
> +export const platformProfessionalsText = 'платформе Профессионалы 4.0';
Это не ссылка

2021-09-14 11:06 UTC, gizeasy commented on src/pages/MainPage/FAQ/data.tsx
> +            {platformProfessionalsText}
в чем был смысл выносить текст ссылки?

2021-09-14 11:25 UTC, N1MBER commented on src/pages/MainPage/FAQ/data.tsx
> +            {platformProfessionalsText}
Убрал все [в этом коммите](https://github.com/gazprom-neft/consta-landing/pull/14/commits/41f56640cbfb381e72885f0891a62867be60e362)

2021-09-15 16:18 UTC, gizeasy approved these changes

2021-09-15 16:18 UTC, merged